### ISSUE TITLE
朋友，求助。。

### ISSUE THREAD

**Issue by coneycode** [chenxiaoyu3/BBStockChartView#1]
这个chart有没有单独的例子？
另外方便留个联系方式交流吗？
多谢。

**Comment by chenxiaoyu3** [comment]
里面有个demo，就是怎么画这个例图的。。。很简单的

是有啥bug没？

2015-06-12 12:39 GMT+08:00 coney notifications@github.com:

**Comment by coneycode** [comment]
囧，搞定了，我2了，我看你的markdown，直接过去读你的那个比特币项目了，没看这个demo。
另外，是有个bug。我从android转iOS，本来就不太熟，给你添麻烦了，多谢咯~

Axis/AxisY.m的方法里面。- (CGFloat)heighForVal:(CGFloat)val方法，当high和low相同，即为零的时候，你return high-low是个分母，为零系统就挂了。

现在横屏还不能放大缩小对吧？

另外，东西做的很赞~
我是10年哈工大毕业的，13年在港中文做研究助理的时候，差点被boss说动，入坑读博士，哈哈，目前在深圳创业，你还在读书吗?
交个朋友？我微信6572389~

**Comment by chenxiaoyu3** [comment]
放大缩小还没弄，我也是做着玩玩的，一起交流~
我南大研究生，今年马上毕业~ 微信HalfWay

**Comment by coneycode** [comment]
哈，期待放大缩小功能，最近都没机会静下来好好研究代码，好怀念学生时代~
